### PR TITLE
Add Host-Ip-Address AVP in CER

### PR DESCRIPTION
**Pull request by osthyvel**
- AVP is mandatory in CER, see https://tools.ietf.org/html/rfc6733#page-64

### CODE REVIEW

**Comment by bmellstrom** [comment]
Sorry for the late reply; vacation :)
Question: Shouldn't host-ip-address be the sending computer's IP address, meaning it could be set to the same value as the bind address from main()? Regardless, it seems unnecessary to parse the IP each time in handle_cer(), better to do it once from main() and be done with it.

**Comment by osthyvel** [comment]
The bind address is 0.0.0.0 and therefore it's useful to be able to configure the host address. I've now changed so that the address is parsed once when reading the config. The limitation that we currently only support IPv4 addresses for the host ip remains.

**Comment by bmellstrom** [comment]
Hm, how about using the current local endpoint address instead then? Something like this:
https://github.com/bmellstrom/ocs-server-dummy/commit/1f1b29b42a38dc708151246b231984cdbfe50eb6

It seems a bit strange to set 0.0.0.0 as listen address and then reply with a single static value; might as well return the ip address of the current interface then, right?

**Comment by osthyvel** [comment]
True, your solution looks good and works fine for me.
Will you pull that to master?

**Comment by bmellstrom** [comment]
Done! Closing this PR :)

**Pull request closed without merging**
